version: "3.9"
services:
  backend:
    build: ./backend
    container_name: cbk-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - API_KEY=${API_KEY}
    restart: always

  frontend:
    build: ./frontend
    container_name: cbk-frontend
    ports:
      - "5173:80"
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_API_KEY=${VITE_API_KEY}
    depends_on:
      - backend
    restart: always